name: Build Kernel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up compiler
      run: sudo apt install clang gcc make -y
    - name: Build Kernel
      run: |
        make O=out dandelion_defconfig
        make -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: kernel-build
        path: out/arch/arm64/boot/Image.gz-dtb
